apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teller-home-data
  namespace: teller-home
spec:
  # k3s ships with the local-path provisioner as the default storage class
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
